### PR TITLE
proposal for writing collaborative VCV rack tracks

### PR DESCRIPTION
**Pull request by connerk**
outlines a proposal on how we can write VCV Rack tracks collaboratively through Github

### CODE REVIEW

**Comment by xtagon** [comment]
One immediate challenge is installing all the plugins required for a collaboration. I tried to open brain-dance and was missing a lot of plugins. Could we make some sort of install script that would download them?

**Comment by xtagon** [comment]
Hmm, nevermind. It is easier than I thought to install the plugins and there aren't as many as I thought because they're bundled in packages.

**Comment by connerk** [comment]
nice. did it walk you through it or do you think each track should have a readme of sorts to state which packages are used?

**Comment by xtagon** [comment]
Instead of opening the file it showed an error window with a list of the missing plugins. I had to create an account, add them to my account, and then sign into VCV rack and update

**Pull request merged**
